site_name: EveryVoice TTS Toolkit Documentation
site_url: https://docs.everyvoice.ca
repo_url: https://github.com/EveryVoiceTTS/EveryVoice
repo_name: EveryVoiceTTS/EveryVoice
theme:
  name: material
  favicon: favicon-32x32.png
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - primary: blue
      accent: light blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - announce.dismiss
    - content.footnote.tooltips
    - navigation.instant
    - navigation.footer
plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [everyvoice]
extra:
  homepage: https://docs.everyvoice.ca
  version:
    provider: mike
    default: stable
markdown_extensions:
  - mkdocs-typer
  - mkdocs-click
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Getting Started: index.md
  - Installation: install.md
  - Guides:
    - Getting Started: guides/index.md
    - Ethical Considerations and Consequences of TTS: guides/ethics.md
    - Background to TTS: guides/background.md
    - Customize to your language: guides/custom.md
    - How to fine-tune: guides/finetune.md
  - Reference:
    - How to use: reference/index.md
    - Configuration: reference/configuration.md
  - Advanced:
    - How to Setup Code Completion for Schemas in vim: guides/schemas.md
