aligner:
  model:
    lstm_dim: 512
    conv_dim: 512
  training:
    optimizer:
      learning_rate: 1e-4
      eps: 1e-8
      weight_decay: 0.01
      betas: [0.9, 0.98]
      name: adamw
    binned_sampler: True
    plot_steps: 1000
    extraction_method: "beam"
    batch_size: 32
    train_split: 0.99
    save_top_k_ckpts: 3
    ckpt_steps: null
    ckpt_epochs: 1
    max_epochs: 1000
    seed: 1234
    finetune_checkpoint: null
    filelist: "./preprocessed/YourDataSet/processed_filelist.psv"
    filelist_loader: "smts.utils.generic_dict_loader"
    logger:
      name: "Base Experiment"
      save_dir: "./logs"
      sub_dir: "smts.utils.get_current_time"
      version: "base"
    val_data_workers: 0
    train_data_workers: 0
  preprocessing:
    dataset: "YourDataSet"
    pitch_type: "pyworld"
    pitch_phone_averaging: True
    energy_phone_averaging: True
    value_separator: "--"
    save_dir: "./preprocessed/YourDataSet"
    audio:
      min_audio_length: 0.25
      max_audio_length: 11.0
      max_wav_value: 32768.0
      norm_db: -3.0
      sil_threshold: 1.0
      sil_duration: 0.1
      input_sampling_rate: 22050
      output_sampling_rate: 22050
      alignment_sampling_rate: 22050
      target_bit_depth: 16
      alignment_bit_depth: 16
      fft_window_frames: 1024
      fft_hop_frames: 256
      f_min: 0
      f_max: 8000
      n_fft: 1024
      n_mels: 80
      spec_type: "mel-librosa"
      vocoder_segment_size: 8192
    source_data:
      - label: "LJ_TEST"
        data_dir: "./tests/data/lj/wavs"
        textgrid_dir: "./tests/data/lj/textgrids"
        filelist_loader: "smts.utils.load_lj_metadata_hifigan" # TODO: sort out callables
        filelist: "./filelists/lj_full.psv"
        sox_effects:
          - ["channels", "1"]  # convert to mono
          - ["rate", "16000"]  # resample
          - ["norm", "-3.0"]  # normalize to -3 dB
          - # remove silence throughout the file
            - "silence"
            - "1"  # Above periods silence; ie. allow 1 second of silence at beginning
            - "0.1"  # Above periods silence duration
            - "1.0%"  # Above periods silence threshold
            - "-1"  # See https://linux.die.net/man/1/sox#:~:text=To%20remove%20silence,of%20the%20audio.
            - "0.1"  # Below periods silence duration
            - "1.0%"  # Below periods silence threshold
  text:
    cleaners:
      - smts.utils.lower
      - smts.utils.collapse_whitespace
      - smts.utils.nfc_normalize
    symbols:
      silence: ["<SIL>"]
      pad: "_"
      punctuation: "-';:,.!?¡¿—…\"«»“” "
      lowercase_letters: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
      uppercase_letters: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
feature_prediction:
  model:
    encoder:
      layers: 4
      heads: 2
      hidden_dim: 256
      feedforward_dim: 1024
      conv_filter_size: 1024
      conv_kernel_size: 9
      dropout: 0.2
      depthwise: True
      conformer: True
    decoder:
      layers: 6
      heads: 2
      hidden_dim: 256
      feedforward_dim: 1024
      conv_filter_size: 1024
      conv_kernel_size: 9
      dropout: 0.2
      depthwise: True
      conformer: True
    variance_adaptor:
      variance_predictors:
        pitch:
          level: "phone"
          transform: "none"
          loss: "mse"
          n_layers: 5
          loss_weights: 5e-2
          kernel_size: 3
          dropout: 0.5
          hidden_dim: 256
          n_bins: 256
          depthwise: True
        energy:
          level: "phone"
          transform: "none"
          loss: "mse"
          n_layers: 5
          loss_weights: 5e-2
          kernel_size: 3
          dropout: 0.5
          hidden_dim: 256
          n_bins: 256
          depthwise: True
        duration:
          transform: "none"
          loss: "mse"
          n_layers: 5
          loss_weights: 5e-2
          kernel_size: 3
          dropout: 0.5
          hidden_dim: 256
          n_bins: 256
          depthwise: True
    learn_alignment: False
    max_length: 1000
    mel_loss: "mse"
    mel_loss_weight: 5e-1
    phonological_feats_size: 38
    use_phonological_feats: False
    use_postnet: True
    multilingual: True
    multispeaker:
      embedding_type: "id"
      every_layer: False
      dvector_gmm: False
  training:
    use_weighted_sampler: False
    freeze_layers:
      encoder: False
      decoder: False
      postnet: False
      variance:
        energy: False
        duration: False
        pitch: False
    optimizer:
      learning_rate: 1e-4
      eps: 1e-8
      weight_decay: 0.01
      betas: [0.9, 0.98]
      warmup_steps: 4000
    early_stopping:
      metric: "none"
      patience: 4
    tf:
      ratio: 1.0
      linear_schedule: False
      linear_schedule_start: 0
      linear_schedule_end: 20
      linear_schedule_end_ratio: 0.0
    batch_size: 16
    train_split: 0.9
    save_top_k_ckpts: 5
    ckpt_steps: null
    ckpt_epochs: 1
    max_epochs: 1000
    seed: 1234
    finetune_checkpoint: null
    filelist: "./preprocessed/YourDataSet/processed_filelist.psv"
    filelist_loader: "smts.utils.generic_dict_loader"
    logger:
      name: "Base Experiment"
      save_dir: "./logs"
      sub_dir: "smts.utils.get_current_time"
      version: "base"
    val_data_workers: 0
    train_data_workers: 0
  preprocessing:
    dataset: "YourDataSet"
    pitch_type: "pyworld"
    pitch_phone_averaging: True
    energy_phone_averaging: True
    value_separator: "--"
    save_dir: "./preprocessed/YourDataSet"
    audio:
      min_audio_length: 0.25
      max_audio_length: 11.0
      max_wav_value: 32768.0
      norm_db: -3.0
      sil_threshold: 1.0
      sil_duration: 0.1
      input_sampling_rate: 22050
      output_sampling_rate: 22050
      alignment_sampling_rate: 22050
      target_bit_depth: 16
      alignment_bit_depth: 16
      fft_window_frames: 1024
      fft_hop_frames: 256
      f_min: 0
      f_max: 8000
      n_fft: 1024
      n_mels: 80
      spec_type: "mel-librosa"
      vocoder_segment_size: 8192
    source_data:
      - label: "LJ_TEST"
        data_dir: "./tests/data/lj/wavs"
        textgrid_dir: "./tests/data/lj/textgrids"
        filelist_loader: "smts.utils.load_lj_metadata_hifigan" # TODO: sort out callables
        filelist: "./filelists/lj_full.psv"
        sox_effects:
          - ["channels", "1"]  # convert to mono
          - ["rate", "16000"]  # resample
          - ["norm", "-3.0"]  # normalize to -3 dB
          - # remove silence throughout the file
            - "silence"
            - "1"  # Above periods silence; ie. allow 1 second of silence at beginning
            - "0.1"  # Above periods silence duration
            - "1.0%"  # Above periods silence threshold
            - "-1"  # See https://linux.die.net/man/1/sox#:~:text=To%20remove%20silence,of%20the%20audio.
            - "0.1"  # Below periods silence duration
            - "1.0%"  # Below periods silence threshold
  text:
    cleaners:
      - smts.utils.lower
      - smts.utils.collapse_whitespace
      - smts.utils.nfc_normalize
    symbols:
      silence: ["<SIL>"]
      pad: "_"
      punctuation: "-';:,.!?¡¿—…\"«»“” "
      lowercase_letters: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
      uppercase_letters: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
vocoder:
  model:
    resblock: "1"
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    depthwise_separable_convolutions:
      generator: False
    activation_function: "smts.utils.original_hifigan_leaky_relu"
    istft_layer: False
  training:
    generator_warmup_steps: 0
    gan_type: "original"
    optimizer:
      learning_rate: 1e-4
      eps: 1e-8
      weight_decay: 0.01
      betas: [0.9, 0.98]
      name: adamw
    wgan_clip_value: 0.01
    use_weighted_sampler: False
    batch_size: 16
    train_split: 0.9
    save_top_k_ckpts: 5
    ckpt_steps: null
    ckpt_epochs: 1
    max_epochs: 1000
    seed: 1234
    finetune_checkpoint: null
    filelist: "./preprocessed/YourDataSet/processed_filelist.psv"
    filelist_loader: "smts.utils.generic_dict_loader"
    logger:
      name: "Base Experiment"
      save_dir: "./logs"
      sub_dir: "smts.utils.get_current_time"
      version: "base"
    val_data_workers: 0
    train_data_workers: 0
  preprocessing:
    dataset: "YourDataSet"
    pitch_type: "pyworld"
    pitch_phone_averaging: True
    energy_phone_averaging: True
    value_separator: "--"
    save_dir: "./preprocessed/YourDataSet"
    audio:
      min_audio_length: 0.25
      max_audio_length: 11.0
      max_wav_value: 32768.0
      norm_db: -3.0
      sil_threshold: 1.0
      sil_duration: 0.1
      input_sampling_rate: 22050
      output_sampling_rate: 22050
      alignment_sampling_rate: 22050
      target_bit_depth: 16
      alignment_bit_depth: 16
      fft_window_frames: 1024
      fft_hop_frames: 256
      f_min: 0
      f_max: 8000
      n_fft: 1024
      n_mels: 80
      spec_type: "mel-librosa"
      vocoder_segment_size: 8192
    source_data:
      - label: "LJ_TEST"
        data_dir: "./tests/data/lj/wavs"
        textgrid_dir: "./tests/data/lj/textgrids"
        filelist_loader: "smts.utils.load_lj_metadata_hifigan" # TODO: sort out callables
        filelist: "./filelists/lj_full.psv"
        sox_effects:
          - ["channels", "1"]  # convert to mono
          - ["rate", "16000"]  # resample
          - ["norm", "-3.0"]  # normalize to -3 dB
          - # remove silence throughout the file
            - "silence"
            - "1"  # Above periods silence; ie. allow 1 second of silence at beginning
            - "0.1"  # Above periods silence duration
            - "1.0%"  # Above periods silence threshold
            - "-1"  # See https://linux.die.net/man/1/sox#:~:text=To%20remove%20silence,of%20the%20audio.
            - "0.1"  # Below periods silence duration
            - "1.0%"  # Below periods silence threshold
