name: Deploy docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/docs.yml
      - everyvoice/config/text_config.py
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  docs:
    # Create latest docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to push to gh-pages branch
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0 # fetch all commits/branches
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies and package
        run: |
          CUDA_TAG=cpu pip install -r requirements.torch.txt --find-links https://download.pytorch.org/whl/torch_stable.html
          pip install -e .[docs]
      - name: Setup doc deploy
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs with mike 🚀
        run: |
          mike deploy --update-aliases dev latest
      - name: Push only if there was a contentful change
        run: |
          if git diff --name-only origin/gh-pages gh-pages | grep -v dev/sitemap.xml; then
            echo Pushing real changes
            git push origin gh-pages
          else
            echo No contentful changes to push
          fi
