name: Run Matrix Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: read

jobs:
  matrix-ubuntu:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: sox
      - uses: FedericoCarboni/setup-ffmpeg@37062fbf7149fc5578d6c57e08aed62458b375d6 # @v3.1, with tool cache
      - name: Install dependencies and EveryVoice itself
        run: |
          CUDA_TAG=cpu pip install -r requirements.torch.txt --find-links https://download.pytorch.org/whl/torch_stable.html
          pip install -e .[dev]
      - run: pip freeze
      - run: pip list
      - run: pytest

  matrix-macos:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - run: brew install ffmpeg sox
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -e .[dev]
      - run: python --version
      - run: pip freeze
      - run: pip list
      - run: pytest
