name: Run Matrix Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: read

jobs:
  matrix-ubuntu:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: sox
      - uses: FedericoCarboni/setup-ffmpeg@37062fbf7149fc5578d6c57e08aed62458b375d6 # @v3.1, with tool cache
        id: ffmpeg
        continue-on-error: true
      - name: Alternate way to install ffmpeg if need be
        if: steps.ffmpeg.outcome == 'failure'
        run: sudo apt-get update && sudo apt-get install ffmpeg
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.8"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - run: uv pip freeze
      - run: uv pip list
      - run: uv run pytest

  matrix-macos:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - run: brew install ffmpeg sox
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.8"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - run: uv pip freeze
      - run: uv pip list
      - run: uv run pytest
