name: Run Tests
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SGILE_PAT }}
          submodules: recursive
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Install Conda Deps
        run: |
          conda install -c conda-forge sox
          conda install pytorch torchaudio -c pytorch
      - name: Install libsndfile
        run: sudo apt-get install -y libsndfile1
      - name: Check licenses
        run: |
          pip3 install pip-licenses
          if pip-licenses | grep -v 'Artistic License' | grep -v LGPL | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi
      - name: Install other dependencies
        run: |
          pip3 install coverage soundfile
          pip3 install -e .
          cd docs && pip3 install -r requirements.txt
      - name: Docs
        run: |
          cd docs && make html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
      - name: Run tests
        run: |
          cd smts && coverage run run_tests.py dev
          coverage xml
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
