name: Run Tests
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SGILE_PAT }}
          submodules: recursive
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Install libsndfile
        run: sudo apt-get install -y libsndfile1
      - name: Install dependencies and package
        run: |
          CUDA_TAG=cu117 pip install -r requirements.torch.txt --find-links https://download.pytorch.org/whl/torch_stable.html
          pip install cython
          pip install -e .
          pip install coverage
          cd docs && pip install -r requirements.txt
      - name: Check licenses
        run: |
          pip install pip-licenses
          if pip-licenses | grep -E -v 'Artistic License|LGPL|Public Domain' | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi
      - name: Docs
        run: |
          cd docs && make html
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'  # only publish the docs from main
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
      - name: Run tests
        run: |
          cd everyvoice && coverage run run_tests.py dev
          coverage xml
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
