name: Run Tests
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SGILE_PAT }}
          submodules: recursive
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Install sox and use conda to optimize other installs
        run: |
          conda install -y sox $(grep "pycountry\|pyworld" requirements.txt) -c conda-forge
      - name: Install dependencies and package
        run: |
          CUDA_TAG=cpu pip install -r requirements.torch.txt --find-links https://download.pytorch.org/whl/torch_stable.html
          pip install -r requirements.test.txt
          pip install cython
          pip install -e .
          pip install coverage
      - name: Check licenses
        run: |
          pip install pip-licenses
          if pip-licenses | grep -E -v 'Artistic License|LGPL|Public Domain' | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi
      - name: Run tests
        run: |
          cd everyvoice && coverage run run_tests.py dev
          coverage xml
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Make sure the CLI stays fast
        id: cli-load-time
        run: |
          CLI_LOAD_TIME="$((/usr/bin/time --format=%E everyvoice -h > /dev/null) 2>&1)"
          echo "CLI load time: $CLI_LOAD_TIME"
          echo "CLI_LOAD_TIME=$CLI_LOAD_TIME" >> $GITHUB_OUTPUT
          if [[ "$CLI_LOAD_TIME" > "0:01.00" ]]; then \
            echo "ERROR: everyvoice --help is too slow."; \
            echo "Please make sure any expensive imports are tucked away so that the CLI doesn't load them until it uses them."; \
            false; \
          fi
      - name: Report help speed in PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            CLI load time is ${{ steps.cli-load-time.outputs.CLI_LOAD_TIME }}
            PR head "${{ github.event.pull_request.head.sha }}"
